### ISSUE TITLE
Git not working properly with updated docker image

### ISSUE THREAD

**Issue by fcatalan92** [alidock/alipier#20]
After the recent update of the image I'm not able anymore to compile O2 and AliPhysics. The error is related to git:
```
/opt/rh/rh-git218/root/usr/libexec/git-core/git-remote-https: error while loading shared libraries: 
libcurl-httpd24.so.4: cannot open shared object file: No such file or directory`
```
it can be fixed calling 
```
source scl_source enable httpd24
```
before aliBuild.

@ktf could this be fixed adding the source in the [slc7-builder](https://github.com/alisw/docks/blob/master/slc7-builder/provision.sh) ?

**Comment by mconcas** [comment]
Thanks for reporting, Fabio.
I'll have a look now, I guess this can not be fixed at container image level.
I'm figuring out the most reliable way to fix this.

Thanks!

**Comment by mconcas** [comment]
Update: turns out to be some misconfiguration in Fabio's environment.
Closing.
